# Kein automatischer Branch-Trigger – der Start erfolgt über den Service Hook
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Optional: Falls du weitere Build- oder Testschritte brauchst, füge sie hier ein

# Deployment in die Azure Web App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AzDevOps-EmailBuilder-JS'   # Ersetze diesen Platzhalter
    appType: 'webApp'
    WebAppName: 'email-builder-js'             # Ersetze diesen Platzhalter
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*'
